# Generated by Django 5.2.14 on 2026-05-07 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contexts", "0001_initial"),
        ("documents", "0001_initial"),
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "campaign_level",
                    models.CharField(
                        choices=[
                            ("listing_only", "Listing Only"),
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("full", "Full"),
                            ("strategic", "Strategic"),
                            ("schools_outreach", "Schools Outreach"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operating_context",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignDeliverable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deliverable_type",
                    models.CharField(
                        choices=[
                            ("pr_plan", "PR Plan"),
                            ("poster_design", "Poster Design"),
                            ("social_media_plan", "Social Media Plan"),
                            ("website_page", "Website Page"),
                            ("newsletter", "Newsletter"),
                            ("photo_shoot", "Photo Shoot"),
                            ("video_shoot", "Video Shoot"),
                            ("programme_booklet", "Programme Booklet"),
                            ("press_release", "Press Release"),
                            ("school_mailer", "School Mailer"),
                            ("brand_toolkit", "Brand Toolkit"),
                            ("design_brief", "Design Brief"),
                            ("advertising_plan", "Advertising Plan"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("owner_name", models.CharField(max_length=255)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("planning", "Planning"),
                            ("in_progress", "In Progress"),
                            ("review", "Review"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="marketing.campaign",
                    ),
                ),
                (
                    "evidence_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliverable_evidence",
                        to="documents.document",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "created_at"],
            },
        ),
    ]
