# Generated by Django 5.2.14 on 2026-05-19 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("marketing", "0001_initial"),
        ("organisations", "0002_organisation_popia_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudienceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_attendance", models.PositiveIntegerField(default=0)),
                ("capacity_total", models.PositiveIntegerField(default=0)),
                ("comps_issued", models.PositiveIntegerField(default=0)),
                ("school_groups", models.PositiveIntegerField(default=0)),
                (
                    "average_ticket_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "gross_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("demographics_notes", models.TextField(blank=True)),
                ("feedback_summary", models.TextField(blank=True)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("is_finalised", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operating_context",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience_report",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "X / Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email Newsletter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("media_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("reach", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("engagements", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_posts",
                        to="marketing.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
    ]
