# Generated by Django 5.2.14 on 2026-05-06 16:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        ("structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("venue_rental", "Venue Rental"),
                            ("co_production", "Co-Production"),
                            ("youth_project", "Youth Project"),
                            ("festival", "Festival"),
                            ("workshop_series", "Workshop Series"),
                            ("civic_event", "Civic Event"),
                            ("governance_item", "Governance Item"),
                        ],
                        default="production",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("confirmed", "Confirmed"),
                            ("in_production", "In Production"),
                            ("in_delivery", "In Delivery"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("synopsis", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("opening_date", models.DateField(blank=True, null=True)),
                ("closing_date", models.DateField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "actual_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ticketing_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("webtickets", "Webtickets"),
                            ("computicket", "Computicket"),
                            ("ticketpro", "Ticketpro"),
                            ("internal_rsvp", "Internal RSVP"),
                            ("not_ticketed", "Not Ticketed"),
                            ("to_confirm", "To Confirm"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "campaign_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("listing_only", "Listing Only"),
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("full", "Full"),
                            ("strategic", "Strategic"),
                            ("schools_outreach", "Schools Outreach"),
                        ],
                        max_length=20,
                    ),
                ),
                ("kpi_link", models.CharField(blank=True, max_length=255)),
                (
                    "readiness_score",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operating_contexts",
                        to="structure.department",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_contexts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_contexts",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "primary_space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operating_contexts",
                        to="structure.space",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operating_contexts",
                        to="structure.site",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operating_contexts",
                        to="structure.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
