# Generated by Django 5.2.14 on 2026-05-22 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contexts", "0001_initial"),
        ("organisations", "0003_entity_config"),
        ("structure", "0005_rental_booking_invoice_resident"),
    ]

    operations = [
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "edition",
                    models.CharField(
                        blank=True, help_text="e.g. 2025 or 12th Edition", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("open_submissions", "Open for Programme Submissions"),
                            ("programme_finalised", "Programme Finalised"),
                            ("accreditation_open", "Accreditation Open"),
                            ("in_progress", "Festival in Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=25,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("artistic_director", models.CharField(blank=True, max_length=255)),
                ("expected_attendance", models.PositiveIntegerField(default=0)),
                ("max_accreditation", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FestivalPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("full_festival", "Full Festival Pass"),
                            ("day_pass", "Day Pass"),
                            ("artist", "Artist / Performer"),
                            ("press", "Press / Media"),
                            ("accreditation", "Industry Accreditation"),
                            ("vip", "VIP / Sponsor"),
                            ("crew", "Crew / Production"),
                            ("volunteer", "Volunteer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("holder_name", models.CharField(max_length=255)),
                ("holder_email", models.EmailField(blank=True, max_length=254)),
                ("organisation_name", models.CharField(blank=True, max_length=255)),
                ("pass_number", models.CharField(blank=True, max_length=50)),
                (
                    "valid_days",
                    models.CharField(
                        blank=True,
                        help_text='Comma-separated dates or "all"',
                        max_length=255,
                    ),
                ),
                (
                    "venue_access",
                    models.CharField(
                        blank=True, help_text='Venue codes or "all"', max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "festival",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passes",
                        to="festivals.festival",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FestivalVenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "venue_code",
                    models.CharField(
                        blank=True, help_text="Short code e.g. MH, ST", max_length=10
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "festival",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="festivals.festival",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="festival_venues",
                        to="structure.venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FestivalVenueSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slot_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_label", models.CharField(blank=True, max_length=100)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "festival",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_slots",
                        to="festivals.festival",
                    ),
                ),
                (
                    "festival_venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="festivals.festivalvenue",
                    ),
                ),
                (
                    "operating_context",
                    models.ForeignKey(
                        blank=True,
                        help_text="The show/performance scheduled in this slot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="festival_slots",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["slot_date", "start_time"],
            },
        ),
    ]
