# Generated by Django 5.2.14 on 2026-05-20 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_entity_config"),
        ("suppliers", "0002_purchase_requisition_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierCSDVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("csd_supplier_number", models.CharField(blank=True, max_length=100)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("not_verified", "Not Verified"),
                            ("pending", "Verification Pending"),
                            ("verified", "Verified on CSD"),
                            ("failed", "Verification Failed"),
                            ("expired", "Verification Expired (>30 days)"),
                            ("excluded", "Excluded / Blocked Supplier"),
                        ],
                        default="not_verified",
                        max_length=20,
                    ),
                ),
                ("verification_date", models.DateField(blank=True, null=True)),
                (
                    "tax_compliance_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compliant", "Tax Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tax_clearance_pin", models.CharField(blank=True, max_length=100)),
                ("tax_clearance_expiry", models.DateField(blank=True, null=True)),
                ("bee_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bee_certificate_expiry", models.DateField(blank=True, null=True)),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("blacklist_reason", models.TextField(blank=True)),
                (
                    "manual_override_notes",
                    models.TextField(
                        blank=True,
                        help_text="Reason if PO approved despite failed CSD check",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csd_verifications",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="csd_verifications_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-verification_date"],
            },
        ),
    ]
