# Generated by Django 5.2.14 on 2026-05-21 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_entity_config"),
        ("structure", "0004_venue_rental"),
        ("suppliers", "0003_csd_verification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreeQuoteRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(max_length=255)),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Quotes Being Collected"),
                            ("quotes_received", "Quotes Received — Evaluating"),
                            ("awarded", "Awarded"),
                            ("cancelled", "Cancelled"),
                            ("waiver_approved", "Single-Source Waiver Approved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("required_by_date", models.DateField(blank=True, null=True)),
                ("budget_line", models.CharField(blank=True, max_length=255)),
                (
                    "awarded_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("award_motivation", models.TextField(blank=True)),
                ("waiver_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "awarded_to_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_quotes",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_requirements",
                        to="structure.department",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waiver_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_waivers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True,
                        help_text="Free-text if supplier not on system",
                        max_length=255,
                    ),
                ),
                ("quote_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quote_date", models.DateField()),
                ("quote_reference", models.CharField(blank=True, max_length=100)),
                ("is_preferred", models.BooleanField(default=False)),
                ("disqualified", models.BooleanField(default=False)),
                ("disqualification_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_quotes",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="suppliers.threequoterequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["quote_amount"],
            },
        ),
    ]
