# Generated by Django 5.2.14 on 2026-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
