# Generated by Django 5.2.14 on 2026-05-22 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("organisations", "0003_entity_config"),
        ("technical", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CueSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("lx", "Lighting (LX)"),
                            ("sq", "Sound (SQ)"),
                            ("fly", "Fly / Flying"),
                            ("auto", "Automation"),
                            ("proj", "Projection / Video"),
                            ("pyro", "Pyrotechnics / SFX"),
                            ("sm", "Stage Management"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_master", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cue_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operating_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cue_sheets",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_cue_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["department", "version"],
            },
        ),
        migrations.CreateModel(
            name="CueLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cue_number",
                    models.CharField(help_text="e.g. Q1, LX-01, SQ-003", max_length=20),
                ),
                ("page_ref", models.CharField(blank=True, max_length=20)),
                ("action", models.TextField()),
                ("standby_note", models.CharField(blank=True, max_length=255)),
                ("follow_on", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "cue_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="technical.cuesheet",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "cue_number"],
            },
        ),
        migrations.CreateModel(
            name="PropsItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("furniture", "Furniture"),
                            ("hand_prop", "Hand Prop"),
                            ("set_dressing", "Set Dressing"),
                            ("weapon", "Weapon / Replica"),
                            ("food", "Food / Edible"),
                            ("electrical", "Electrical Prop"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair — Minor Repairs Needed"),
                            ("poor", "Poor — Repair Required"),
                            ("written_off", "Written Off"),
                        ],
                        default="good",
                        max_length=15,
                    ),
                ),
                ("storage_location", models.CharField(blank=True, max_length=255)),
                ("is_hired", models.BooleanField(default=False)),
                ("hire_company", models.CharField(blank=True, max_length=255)),
                (
                    "hire_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("hire_return_date", models.DateField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_production",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="props",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WardrobeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("costume", "Costume"),
                            ("accessory", "Accessory"),
                            ("footwear", "Footwear"),
                            ("headwear", "Headwear"),
                            ("wig", "Wig / Hair"),
                            ("makeup", "Makeup"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("character", models.CharField(blank=True, max_length=255)),
                ("size", models.CharField(blank=True, max_length=50)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair — Minor Repairs Needed"),
                            ("poor", "Poor — Repair Required"),
                            ("written_off", "Written Off"),
                        ],
                        default="good",
                        max_length=15,
                    ),
                ),
                ("is_hired", models.BooleanField(default=False)),
                ("hire_company", models.CharField(blank=True, max_length=255)),
                (
                    "hire_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("hire_return_date", models.DateField(blank=True, null=True)),
                ("assigned_to_performer", models.CharField(blank=True, max_length=255)),
                ("storage_location", models.CharField(blank=True, max_length=255)),
                ("cleaning_required", models.BooleanField(default=False)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_production",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wardrobe_items",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
