# Generated by Django 5.2.14 on 2026-05-11 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
        ('organisations', '0001_initial'),
        ('programming', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('venue_booking', 'Venue Booking Request'), ('production_proposal', 'Production Proposal'), ('co_production_proposal', 'Co-Production Proposal'), ('youth_programme_proposal', 'Youth Programme Proposal'), ('festival_request', 'Festival Request'), ('workshop_series_request', 'Workshop Series Request'), ('training_programme_request', 'Training Programme Request'), ('civic_event_request', 'Civic Event Request'), ('governance_item_request', 'Governance Item Request'), ('internal_programming_request', 'Internal Programming Request')], max_length=40)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('deferred', 'Deferred'), ('approved', 'Approved'), ('declined', 'Declined'), ('converted', 'Converted'), ('archived', 'Archived')], default='submitted', max_length=30)),
                ('event_title', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_organisation', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('requested_start_date', models.DateField(blank=True, null=True)),
                ('requested_end_date', models.DateField(blank=True, null=True)),
                ('expected_audience', models.PositiveIntegerField(blank=True, null=True)),
                ('ticketing_required', models.BooleanField(default=False)),
                ('technical_summary', models.TextField(blank=True)),
                ('foh_notes', models.TextField(blank=True)),
                ('accessibility_requirements', models.TextField(blank=True)),
                ('attachments_note', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_context', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_intake_request', to='contexts.operatingcontext')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_intake_requests', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organisations.organisation')),
                ('preferred_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='structure.venue')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_intake_requests', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_intake_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
