# Generated by Django 5.2.14 on 2026-05-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0003_calendarissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarslot',
            name='expected_audience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarslot',
            name='setup_buffer_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calendarslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarslot',
            name='strike_buffer_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venuehold',
            name='expected_audience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuehold',
            name='setup_buffer_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venuehold',
            name='strike_buffer_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calendarslot',
            name='slot_type',
            field=models.CharField(choices=[('performance', 'Performance'), ('rehearsal', 'Rehearsal'), ('dark_day', 'Dark Day'), ('maintenance', 'Maintenance'), ('blackout', 'Blackout'), ('venue_unavailable', 'Venue Unavailable'), ('load_in', 'Load In'), ('strike', 'Strike'), ('changeover', 'Changeover')], max_length=20),
        ),
    ]
