# Generated by Django 5.2.14 on 2026-05-19 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("organisations", "0002_organisation_popia_fields"),
        (
            "programming",
            "0004_calendarslot_end_time_calendarslot_expected_audience_and_more",
        ),
        ("structure", "0002_position_authority_level_position_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "name"],
                "unique_together": {("organisation", "name", "year")},
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("programming", "In Programming"),
                            ("confirmed", "Confirmed"),
                            ("on_sale", "On Sale"),
                            ("running", "Running"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="programming",
                        max_length=20,
                    ),
                ),
                ("genre", models.CharField(blank=True, max_length=100)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("interval_count", models.PositiveIntegerField(default=0)),
                ("age_restriction", models.CharField(blank=True, max_length=50)),
                ("content_advisory", models.TextField(blank=True)),
                ("synopsis", models.TextField(blank=True)),
                ("producer_name", models.CharField(blank=True, max_length=255)),
                ("is_own_production", models.BooleanField(default=False)),
                ("is_co_production", models.BooleanField(default=False)),
                (
                    "budget_approved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "revenue_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operating_context",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="show",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shows",
                        to="programming.season",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("performance_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("doors_time", models.TimeField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performances",
                        to="structure.space",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performances",
                        to="structure.venue",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="programming.show",
                    ),
                ),
            ],
            options={
                "ordering": ["performance_date", "start_time"],
            },
        ),
    ]
