# Generated by Django 5.2.14 on 2026-05-20 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("organisations", "0003_entity_config"),
        ("programming", "0005_season_show_performance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionLicence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "licensing_body",
                    models.CharField(
                        choices=[
                            ("samro", "SAMRO (Performing Rights)"),
                            ("risa", "RISA (Recording Rights)"),
                            ("capasso", "CAPASSO (Composers & Authors)"),
                            ("dalro", "DALRO (Dramatic/Literary)"),
                            ("filmsa", "FILMSA (Film)"),
                            ("other", "Other Licensing Body"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("required", "Required — Not Applied"),
                            ("applied", "Application Submitted"),
                            ("approved", "Licence Approved"),
                            ("paid", "Licence Fee Paid"),
                            ("received", "Licence Certificate Received"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected / Refused"),
                        ],
                        default="required",
                        max_length=20,
                    ),
                ),
                ("licence_number", models.CharField(blank=True, max_length=100)),
                ("application_date", models.DateField(blank=True, null=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "fee_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fee_paid_date", models.DateField(blank=True, null=True)),
                ("certificate_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operating_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licences",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["operating_context", "licensing_body"],
                "unique_together": {
                    ("organisation", "operating_context", "licensing_body")
                },
            },
        ),
    ]
