# Generated by Django 5.2.14 on 2026-05-22 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("organisations", "0003_entity_config"),
        ("programming", "0007_production_journal"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoProducer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("partner_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead_producer", "Lead Producer"),
                            ("co_producer", "Co-Producer"),
                            ("presenting_partner", "Presenting Partner"),
                            ("funding_partner", "Funding Partner"),
                            ("touring_partner", "Touring Partner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "cost_share_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% of total costs borne by this partner",
                        max_digits=5,
                    ),
                ),
                (
                    "revenue_share_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% of net revenue due to this partner",
                        max_digits=5,
                    ),
                ),
                (
                    "upfront_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operating_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_producers",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoProductionSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("settlement_date", models.DateField()),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_position",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("agreed", "Agreed by All Partners"),
                            ("paid", "Settled / Paid"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("settlement_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operating_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coproduction_settlements",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoProductionSettlementLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "co_producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_lines",
                        to="programming.coproducer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="programming.coproductionsettlement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SetlistWork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("composer", models.CharField(blank=True, max_length=255)),
                ("arranger", models.CharField(blank=True, max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                (
                    "isrc_code",
                    models.CharField(
                        blank=True,
                        help_text="International Standard Recording Code",
                        max_length=20,
                    ),
                ),
                (
                    "iswc_code",
                    models.CharField(
                        blank=True,
                        help_text="International Standard Musical Work Code",
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("is_original_work", models.BooleanField(default=False)),
                ("is_public_domain", models.BooleanField(default=False)),
                (
                    "licensing_body",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("samro", "SAMRO"),
                            ("risa", "RISA"),
                            ("capasso", "CAPASSO"),
                            ("dalro", "DALRO"),
                            ("none", "None Required"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setlist_works",
                        to="programming.performance",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
    ]
