# Generated by Django 5.2.14 on 2026-05-22 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("organisations", "0003_entity_config"),
        ("programming", "0008_setlist_coproduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringProduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("annually", "Annually (same season each year)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("next_occurrence_date", models.DateField(blank=True, null=True)),
                (
                    "auto_create",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-create new OperatingContext on each cycle",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_operating_context",
                    models.ForeignKey(
                        blank=True,
                        help_text="The original production this recurs from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurrence_template",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TouringProduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_outgoing",
                    models.BooleanField(
                        default=True,
                        help_text="True = we are touring out; False = incoming touring production",
                    ),
                ),
                ("tour_manager", models.CharField(blank=True, max_length=255)),
                ("transport_provider", models.CharField(blank=True, max_length=255)),
                ("accommodation_notes", models.TextField(blank=True)),
                (
                    "per_diem_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("technical_advance_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operating_context",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="touring_info",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TouringVenueDate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("venue_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("performance_date", models.DateField()),
                ("load_in_date", models.DateField(blank=True, null=True)),
                ("load_out_date", models.DateField(blank=True, null=True)),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("tentative", "Tentative"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="tentative",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "touring_production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="programming.touringproduction",
                    ),
                ),
            ],
            options={
                "ordering": ["performance_date"],
            },
        ),
    ]
