# Generated by Django 5.2.14 on 2026-05-22 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0003_entity_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GLAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("revenue_exchange", "Revenue — Exchange (GRAP 9)"),
                            (
                                "revenue_non_exchange",
                                "Revenue — Non-Exchange (GRAP 23)",
                            ),
                            ("grants_received", "Grants & Subsidies Received"),
                            ("donations", "Donations & Bequests"),
                            ("expense_employee", "Employee Costs"),
                            ("expense_goods", "Goods & Services"),
                            ("expense_depreciation", "Depreciation & Amortisation"),
                            ("expense_other", "Other Expenses"),
                            ("asset_current", "Current Assets"),
                            ("asset_non_current", "Non-Current Assets"),
                            ("liability_current", "Current Liabilities"),
                            ("liability_non_current", "Non-Current Liabilities"),
                            ("equity", "Net Assets / Equity"),
                            ("deferred_income", "Deferred Income (Conditional Grants)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_control_account", models.BooleanField(default=False)),
                (
                    "grap_standard",
                    models.CharField(
                        blank=True, help_text="e.g. GRAP 23, GRAP 9", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["account_code"],
                "unique_together": {("organisation", "account_code")},
            },
        ),
        migrations.CreateModel(
            name="DeferredIncome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grant_name", models.CharField(max_length=255)),
                ("grantor", models.CharField(max_length=255)),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "recognition_type",
                    models.CharField(
                        choices=[
                            ("unconditional", "Unconditional — Recognised Immediately"),
                            (
                                "conditional",
                                "Conditional — Deferred Until Conditions Met",
                            ),
                            (
                                "performance_based",
                                "Performance-Based — Recognised on Achievement",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_grant_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "amount_recognised",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount_deferred",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("conditions_description", models.TextField(blank=True)),
                ("recognition_date", models.DateField(blank=True, null=True)),
                ("is_fully_recognised", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "gl_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deferred_income",
                        to="finance.glaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GLJournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("entry_date", models.DateField()),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        help_text="Accounting period 1-12"
                    ),
                ),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g. grant_receipt, manual, payroll",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GLJournalLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="finance.glaccount",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.gljournalentry",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
