# Generated by Django 5.2.14 on 2026-05-06 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=20)),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("programming", "Programming"),
                            ("marketing", "Marketing"),
                            ("technical", "Technical"),
                            ("operations", "Operations"),
                            ("finance", "Finance"),
                            ("contracts", "Contracts"),
                            ("ticketing", "Ticketing"),
                            ("youth", "Youth"),
                            ("governance", "Governance"),
                            ("executive", "Executive"),
                            ("ict", "ICT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("executive", "Executive"),
                            ("senior_manager", "Senior Manager"),
                            ("manager", "Manager"),
                            ("officer", "Officer"),
                            ("coordinator", "Coordinator"),
                            ("assistant", "Assistant"),
                            ("intern", "Intern"),
                            ("external", "External"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="structure.department",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="structure.position",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="structure.site",
                    ),
                ),
            ],
            options={
                "ordering": ["department", "level", "title"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="structure.site",
            ),
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("performance", "Performance"),
                            ("rehearsal", "Rehearsal"),
                            ("workshop", "Workshop"),
                            ("conference", "Conference"),
                            ("outdoor", "Outdoor"),
                            ("multipurpose", "Multipurpose"),
                            ("other", "Other"),
                        ],
                        default="performance",
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="structure.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "name"],
            },
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "space_type",
                    models.CharField(
                        choices=[
                            ("stage", "Stage"),
                            ("auditorium", "Auditorium"),
                            ("foyer", "Foyer"),
                            ("dressing_room", "Dressing Room"),
                            ("loading_bay", "Loading Bay"),
                            ("control_booth", "Control Booth"),
                            ("workshop", "Workshop"),
                            ("studio", "Studio"),
                            ("restaurant", "Restaurant"),
                            ("vip_room", "VIP Room"),
                            ("other", "Other"),
                        ],
                        default="stage",
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("is_bookable", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spaces",
                        to="structure.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["venue", "name"],
            },
        ),
    ]
