# Generated by Django 5.2.14 on 2026-05-16 17:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='authority_level',
            field=models.CharField(choices=[('executive', 'Executive'), ('gm', 'General Manager'), ('department_manager', 'Department Manager'), ('department_user', 'Department User'), ('specialist', 'Specialist'), ('read_only', 'Read Only'), ('external', 'External')], default='department_user', max_length=30),
        ),
        migrations.AddField(
            model_name='position',
            name='code',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='position',
            name='is_external_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='is_manager_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='is_specialist_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OrganisationOperatingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('single_venue', 'Single Venue'), ('multi_venue', 'Multi Venue'), ('multi_theatre', 'Multi Theatre'), ('institutional', 'Institutional'), ('festival', 'Festival'), ('custom', 'Custom')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organisations.organisation')),
            ],
            options={
                'ordering': ['organisation', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SOPTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_type', models.CharField(choices=[('production', 'Production'), ('venue_booking', 'Venue Booking'), ('youth_project', 'Youth Project'), ('festival', 'Festival'), ('workshop', 'Workshop'), ('training_programme', 'Training Programme'), ('civic_event', 'Civic Event'), ('governance_item', 'Governance Item'), ('custom', 'Custom')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sop_templates', to='structure.department')),
                ('operating_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sop_templates', to='structure.organisationoperatingmodel')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organisations.organisation')),
            ],
            options={
                'ordering': ['operating_model', 'workspace_type', 'sequence', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserDepartmentMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authority_level', models.CharField(choices=[('executive', 'Executive'), ('gm', 'General Manager'), ('department_manager', 'Department Manager'), ('department_user', 'Department User'), ('specialist', 'Specialist'), ('read_only', 'Read Only'), ('external', 'External')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_manage_department', models.BooleanField(default=False)),
                ('can_assign_work', models.BooleanField(default=False)),
                ('can_approve_work', models.BooleanField(default=False)),
                ('can_view_department_summary', models.BooleanField(default=True)),
                ('can_raise_department_issue', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='structure.department')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organisations.organisation')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='structure.position')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='structure.userdepartmentmembership')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='structure.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', '-is_primary', 'department__name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_key', models.CharField(blank=True, max_length=80)),
                ('record_type', models.CharField(blank=True, max_length=120)),
                ('approval_scope', models.CharField(choices=[('department_work', 'Department Work'), ('department_readiness', 'Department Readiness'), ('workspace_conversion', 'Workspace Conversion'), ('contract_review', 'Contract Review'), ('supplier_readiness', 'Supplier Readiness'), ('youth_sensitive', 'Youth Sensitive'), ('technical_readiness', 'Technical Readiness'), ('marketing_readiness', 'Marketing Readiness'), ('foh_readiness', 'FOH Readiness'), ('governance_action', 'Governance Action')], max_length=40)),
                ('required_authority_level', models.CharField(choices=[('executive', 'Executive'), ('gm', 'General Manager'), ('department_manager', 'Department Manager'), ('department_user', 'Department User'), ('specialist', 'Specialist'), ('read_only', 'Read Only'), ('external', 'External')], max_length=30)),
                ('allow_executive_override', models.BooleanField(default=True)),
                ('override_requires_reason', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_policies', to='structure.department')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organisations.organisation')),
            ],
            options={
                'ordering': ['department__name', 'approval_scope'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'department', 'module_key', 'record_type', 'approval_scope'), name='unique_approval_policy_scope')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_key', models.CharField(max_length=80)),
                ('record_type', models.CharField(blank=True, max_length=120)),
                ('work_type', models.CharField(blank=True, max_length=120)),
                ('evidence_required', models.BooleanField(default=True)),
                ('accepted_mime_types', models.JSONField(blank=True, default=list)),
                ('requires_review', models.BooleanField(default=False)),
                ('reviewer_authority_level', models.CharField(blank=True, choices=[('executive', 'Executive'), ('gm', 'General Manager'), ('department_manager', 'Department Manager'), ('department_user', 'Department User'), ('specialist', 'Specialist'), ('read_only', 'Read Only'), ('external', 'External')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_rules', to='structure.department')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organisations.organisation')),
            ],
            options={
                'ordering': ['department__name', 'module_key', 'record_type'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'department', 'module_key', 'record_type', 'work_type'), name='unique_evidence_rule_scope')],
            },
        ),
        migrations.CreateModel(
            name='ModuleActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organisations.organisation')),
            ],
            options={
                'ordering': ['module_key'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'module_key'), name='unique_module_activation_per_org')],
            },
        ),
        migrations.AddConstraint(
            model_name='organisationoperatingmodel',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_operating_model_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='soptemplate',
            constraint=models.UniqueConstraint(fields=('organisation', 'operating_model', 'workspace_type', 'department', 'title'), name='unique_sop_template_scope'),
        ),
        migrations.AddConstraint(
            model_name='userdepartmentmembership',
            constraint=models.UniqueConstraint(fields=('organisation', 'user', 'department', 'position'), name='unique_user_department_position_membership'),
        ),
    ]
