# Generated by Django 5.2.14 on 2026-05-20 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_organisation_popia_fields"),
        ("structure", "0002_position_authority_level_position_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueCapacityConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "configuration",
                    models.CharField(
                        choices=[
                            ("theatre", "Theatre (fixed rows)"),
                            ("cabaret", "Cabaret (round tables)"),
                            ("standing", "Standing"),
                            ("thrust", "Thrust"),
                            ("traverse", "Traverse"),
                            ("in_the_round", "In the Round"),
                            ("promenade", "Promenade"),
                            ("flexible", "Flexible"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_configs",
                        to="structure.space",
                    ),
                ),
            ],
            options={
                "ordering": ["configuration"],
                "unique_together": {("space", "configuration")},
            },
        ),
    ]
