# Generated by Django 5.2.14 on 2026-05-22 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_entity_config"),
        ("structure", "0004_venue_rental"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_number", models.CharField(blank=True, max_length=50)),
                ("confirmed_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("setup_in_progress", "Setup in Progress"),
                            ("event_in_progress", "Event in Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("contract_signed", models.BooleanField(default=False)),
                ("contract_signed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="structure.venuerentalenquiry",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="structure.venuerentalquote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit Invoice"),
                            ("balance", "Balance Invoice"),
                            ("full", "Full Invoice"),
                            ("credit_note", "Credit Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vat_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="structure.rentalbooking",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResidentCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("theatre_company", "Theatre Company"),
                            ("dance_company", "Dance Company"),
                            ("music_ensemble", "Music Ensemble"),
                            ("opera_company", "Opera Company"),
                            ("youth_company", "Youth Company"),
                            ("community_company", "Community Company"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active Residency"),
                            ("completed", "Completed"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("prospective", "Prospective / Negotiating"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("artistic_director", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("residency_start_date", models.DateField()),
                ("residency_end_date", models.DateField(blank=True, null=True)),
                (
                    "rehearsal_space_allocation",
                    models.TextField(
                        blank=True, help_text="Spaces and hours allocated per week"
                    ),
                ),
                ("performance_slots_per_year", models.PositiveIntegerField(default=0)),
                (
                    "annual_subsidy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rental_rate_discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("agreement_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resident_companies",
                        to="structure.venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
