# Generated by Django 5.2.14 on 2026-05-22 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_entity_config"),
        ("structure", "0005_rental_booking_invoice_resident"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueHoldExpiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hold_expiry_date", models.DateField()),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_date", models.DateField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hold_expiry",
                        to="structure.venuerentalenquiry",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
