# Generated by Django 5.2.14 on 2026-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("internal_admin", "Internal Admin"),
                    ("executive", "Executive"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("read_only", "Read Only"),
                    ("supplier_external", "Supplier External"),
                    ("artist_external", "Artist External"),
                    ("client_external", "Client External"),
                    ("youth_external", "Youth External"),
                    ("integration_service", "Integration Service"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
