# Generated by Django 5.2.14 on 2026-05-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_dataconsent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataConsent",
        ),
    ]
