# Generated by Django 5.2.14 on 2026-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("missing", "Missing"),
                    ("uploaded", "Uploaded"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="missing",
                max_length=20,
            ),
        ),
    ]
