'use client';

import { FormEvent, useState } from 'react';
import { X } from 'lucide-react';
import { BlockerAlert, labelFromValue, money, ReadinessBadge, RestrictedField } from '@/components/readiness/shared';
import type { DocumentItem, OperatingContextListItem, SalesImportItem, TicketingSetupItem } from '@/lib/api/types';

export type TicketingAction =
  | { kind: 'go-live'; setup: TicketingSetupItem }
  | { kind: 'import-sales'; setup: TicketingSetupItem }
  | { kind: 'settle'; setup: TicketingSetupItem };

export function ticketingBlockers(setup: TicketingSetupItem) {
  const blockers: string[] = [];
  if (!setup.booking_link && setup.provider !== 'not_ticketed') blockers.push('Booking link is missing.');
  if (setup.setup_status !== 'live' && setup.setup_status !== 'closed') blockers.push('Ticketing is not live.');
  if (!setup.sales_imported) blockers.push('Sales have not been imported.');
  if (setup.settlement_status === 'pending' || setup.settlement_status === 'in_progress') blockers.push('Settlement is pending.');
  if (setup.comps_used > setup.comps_allocated) blockers.push('Comps used are over allocation.');
  return blockers;
}

function workspaceName(workspaces: OperatingContextListItem[], id: string) {
  return workspaces.find((workspace) => workspace.id === id)?.title ?? 'Workspace unavailable';
}

export function TicketingFilters({ providers, value, workspaces, onChange }: { providers: string[]; value: { provider: string; setup: string; settlement: string; imported: string; workspace: string; missingLink: boolean; settlementPending: boolean }; workspaces: OperatingContextListItem[]; onChange: (value: { provider: string; setup: string; settlement: string; imported: string; workspace: string; missingLink: boolean; settlementPending: boolean }) => void }) {
  return <section className="grid gap-2 rounded-lg border border-slate-200 bg-white p-3 md:grid-cols-3 xl:grid-cols-7"><select className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700" onChange={(event) => onChange({ ...value, provider: event.target.value })} value={value.provider}><option value="all">All providers</option>{providers.map((provider) => <option key={provider} value={provider}>{labelFromValue(provider)}</option>)}</select><select className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700" onChange={(event) => onChange({ ...value, setup: event.target.value })} value={value.setup}><option value="all">All setup</option><option value="awaiting_setup">Awaiting setup</option><option value="in_progress">In progress</option><option value="live">Live</option><option value="closed">Closed</option></select><select className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700" onChange={(event) => onChange({ ...value, settlement: event.target.value })} value={value.settlement}><option value="all">All settlement</option><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="settled">Settled</option><option value="not_applicable">Not applicable</option></select><select className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700" onChange={(event) => onChange({ ...value, imported: event.target.value })} value={value.imported}><option value="all">All imports</option><option value="imported">Sales imported</option><option value="not_imported">Not imported</option></select><select className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700" onChange={(event) => onChange({ ...value, workspace: event.target.value })} value={value.workspace}><option value="all">All Workspaces</option>{workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.title}</option>)}</select><label className="flex h-10 items-center gap-2 rounded-md border border-slate-200 px-3 text-sm font-semibold text-slate-700"><input checked={value.missingLink} onChange={(event) => onChange({ ...value, missingLink: event.target.checked })} type="checkbox" />Missing link</label><label className="flex h-10 items-center gap-2 rounded-md border border-slate-200 px-3 text-sm font-semibold text-slate-700"><input checked={value.settlementPending} onChange={(event) => onChange({ ...value, settlementPending: event.target.checked })} type="checkbox" />Settlement pending</label></section>;
}

export function TicketingSetupList({ setups, imports, workspaces, onAction }: { setups: TicketingSetupItem[]; imports: SalesImportItem[]; workspaces: OperatingContextListItem[]; onAction: (action: TicketingAction) => void }) {
  return <div className="grid gap-4 xl:grid-cols-2">{setups.map((setup) => <TicketingSetupCard imports={imports.filter((item) => item.ticketing_setup === setup.id)} key={setup.id} onAction={onAction} setup={setup} workspaces={workspaces} />)}</div>;
}

export function TicketingSetupCard({ setup, imports, workspaces, onAction }: { setup: TicketingSetupItem; imports: SalesImportItem[]; workspaces: OperatingContextListItem[]; onAction: (action: TicketingAction) => void }) {
  return <article className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><h2 className="text-base font-bold text-slate-950">{workspaceName(workspaces, setup.operating_context)}</h2><p className="mt-1 text-sm text-slate-500">{labelFromValue(setup.provider)} · <RestrictedField value={setup.booking_link} /></p></div><ReadinessBadge value={setup.setup_status} /></div><dl className="mt-4 grid gap-3 text-sm md:grid-cols-3"><div><dt className="font-bold text-slate-700">Tickets sold</dt><dd className="mt-1 text-slate-600">{setup.tickets_sold}/{setup.tickets_available}</dd></div><div><dt className="font-bold text-slate-700">Comps</dt><dd className="mt-1 text-slate-600">{setup.comps_used}/{setup.comps_allocated}</dd></div><div><dt className="font-bold text-slate-700">Settlement</dt><dd className="mt-1 text-slate-600">{labelFromValue(setup.settlement_status)} · {money(setup.settlement_amount)}</dd></div></dl>{setup.pricing_description ? <p className="mt-3 text-sm text-slate-600">{setup.pricing_description}</p> : null}<div className="mt-4"><BlockerAlert blockers={ticketingBlockers(setup)} /></div><div className="mt-4 rounded-md border border-slate-200 p-3"><h3 className="text-sm font-bold text-slate-900">Sales imports</h3>{imports.length ? <div className="mt-2 space-y-2">{imports.map((item) => <div className="text-sm text-slate-600" key={item.id}>{item.import_date}: {item.tickets_sold} tickets · {money(item.revenue)}</div>)}</div> : <p className="mt-2 text-sm text-slate-500">No sales imports returned.</p>}</div><div className="mt-4 flex flex-wrap gap-2"><button className="h-9 rounded-md bg-blue-600 px-3 text-sm font-bold text-white" onClick={() => onAction({ kind: 'go-live', setup })} type="button">Mark live</button><button className="h-9 rounded-md border border-slate-200 px-3 text-sm font-bold text-slate-700" onClick={() => onAction({ kind: 'import-sales', setup })} type="button">Import sales</button><button className="h-9 rounded-md border border-slate-200 px-3 text-sm font-bold text-slate-700" onClick={() => onAction({ kind: 'settle', setup })} type="button">Settle</button></div></article>;
}

export function TicketingActionDialog({ action, documents, submitting, onClose, onSubmit }: { action: TicketingAction | null; documents: DocumentItem[]; submitting: boolean; onClose: () => void; onSubmit: (values: { tickets: string; revenue: string; amount: string; notes: string; sourceFile: string }) => void }) {
  const [tickets, setTickets] = useState('');
  const [revenue, setRevenue] = useState('');
  const [amount, setAmount] = useState('');
  const [notes, setNotes] = useState('');
  const [sourceFile, setSourceFile] = useState('');
  if (!action) return null;
  const title = action.kind === 'go-live' ? 'Mark ticketing live' : action.kind === 'import-sales' ? 'Import sales' : 'Settle ticketing';
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSubmit({ tickets, revenue, amount, notes, sourceFile }); }
  return <aside className="fixed inset-y-0 right-0 z-50 w-full max-w-md overflow-y-auto border-l border-slate-200 bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-blue-700">Ticketing action</p><h2 className="mt-1 text-xl font-bold text-slate-950">{title}</h2></div><button aria-label="Close ticketing action" className="inline-flex h-9 w-9 items-center justify-center rounded-md border border-slate-200 text-slate-700" onClick={onClose} type="button"><X className="h-4 w-4" /></button></div><form className="mt-5 space-y-4" onSubmit={submit}>{action.kind === 'import-sales' ? <><div><label className="mb-2 block text-sm font-bold text-slate-800" htmlFor="tickets-sold">Tickets sold</label><input className="h-10 w-full rounded-md border border-slate-300 px-3 text-slate-950" id="tickets-sold" onChange={(event) => setTickets(event.target.value)} type="number" value={tickets} /></div><div><label className="mb-2 block text-sm font-bold text-slate-800" htmlFor="ticket-revenue">Revenue</label><input className="h-10 w-full rounded-md border border-slate-300 px-3 text-slate-950" id="ticket-revenue" onChange={(event) => setRevenue(event.target.value)} value={revenue} /></div><div><label className="mb-2 block text-sm font-bold text-slate-800" htmlFor="sales-source-file">Source file</label><select className="h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-slate-950" id="sales-source-file" onChange={(event) => setSourceFile(event.target.value)} required value={sourceFile}><option value="">Select evidence file</option>{documents.map((document) => <option key={document.id} value={document.id}>{document.title}</option>)}</select></div></> : null}{action.kind === 'settle' ? <div><label className="mb-2 block text-sm font-bold text-slate-800" htmlFor="settlement-amount">Settlement amount</label><input className="h-10 w-full rounded-md border border-slate-300 px-3 text-slate-950" id="settlement-amount" onChange={(event) => setAmount(event.target.value)} value={amount} /></div> : null}<div><label className="mb-2 block text-sm font-bold text-slate-800" htmlFor="ticketing-notes">Notes</label><textarea className="min-h-24 w-full rounded-md border border-slate-300 px-3 py-2 text-slate-950" id="ticketing-notes" onChange={(event) => setNotes(event.target.value)} value={notes} /></div><button className="h-10 w-full rounded-md bg-blue-600 px-4 text-sm font-bold text-white disabled:bg-slate-400" disabled={submitting} type="submit">{submitting ? 'Submitting' : title}</button></form></aside>;
}

