# Generated by Django 5.2.14 on 2026-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowstepinstance_approval_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workflowstepinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
