# Generated by Django 5.2.14 on 2026-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="new_value",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="old_value",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="target_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="target_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
