# Generated by Django 5.2.14 on 2026-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditevent_hash_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="record_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
