# Generated by Django 5.2.14 on 2026-05-20 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_organisation_popia_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantEntityConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("pfma_schedule_3a", "PFMA Schedule 3A Public Entity"),
                            ("mfma_municipal", "MFMA Municipal Entity"),
                            ("section_21_npo", "Section 21 NPO"),
                            ("private_company", "Private Company"),
                        ],
                        default="pfma_schedule_3a",
                        max_length=30,
                    ),
                ),
                (
                    "executive_authority",
                    models.CharField(
                        blank=True,
                        help_text="Shareholder/executive authority name",
                        max_length=255,
                    ),
                ),
                (
                    "accounting_authority",
                    models.CharField(
                        blank=True,
                        help_text="Board/accounting authority name",
                        max_length=255,
                    ),
                ),
                ("auditor_general_client", models.BooleanField(default=True)),
                ("pfma_applicable", models.BooleanField(default=True)),
                ("mfma_applicable", models.BooleanField(default=False)),
                ("grap_reporting", models.BooleanField(default=True)),
                ("treasury_reporting_required", models.BooleanField(default=True)),
                ("shareholder_compact_required", models.BooleanField(default=True)),
                ("delegation_framework_required", models.BooleanField(default=True)),
                (
                    "financial_year_end",
                    models.CharField(
                        default="03-31", help_text="MM-DD format", max_length=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Configuration",
                "unique_together": {("organisation",)},
            },
        ),
    ]
