# Generated by Django 5.2.14 on 2026-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_notification_improvements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task Assigned"),
                    ("task_updated", "Task Updated"),
                    ("task_blocked", "Task Blocked"),
                    ("task_completed", "Task Completed"),
                    ("department_issue", "Department Issue"),
                    ("evidence_rejected", "Evidence Rejected"),
                    ("approval_decided", "Approval Decision"),
                    ("task_overdue", "Task Overdue"),
                    ("workflow_blocked", "Workflow Step Blocked"),
                    ("executive_action", "Executive Action"),
                    ("contract_expiring", "Contract Expiring"),
                    ("supplier_doc_rejected", "Supplier Document Rejected"),
                    ("artist_doc_rejected", "Artist Document Rejected"),
                    ("youth_consent_expiring", "Youth Consent Expiring"),
                ],
                max_length=40,
            ),
        ),
    ]
