# Generated by Django 5.2.14 on 2026-05-19 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("operations", "0001_initial"),
        ("organisations", "0002_organisation_popia_fields"),
        ("programming", "0005_season_show_performance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostShowReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("show_date", models.DateField()),
                ("actual_start_time", models.TimeField(blank=True, null=True)),
                ("actual_end_time", models.TimeField(blank=True, null=True)),
                ("actual_audience", models.PositiveIntegerField(default=0)),
                ("walk_ins", models.PositiveIntegerField(default=0)),
                ("comps_used", models.PositiveIntegerField(default=0)),
                ("incidents_count", models.PositiveIntegerField(default=0)),
                ("technical_issues", models.TextField(blank=True)),
                ("foh_summary", models.TextField(blank=True)),
                ("audience_feedback", models.TextField(blank=True)),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "cash_collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "card_collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operating_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="post_show_reports",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_show_reports",
                        to="programming.performance",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="post_show_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-show_date"],
            },
        ),
        migrations.CreateModel(
            name="ShowCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("show_date", models.DateField()),
                ("call_time", models.TimeField()),
                ("house_open_time", models.TimeField(blank=True, null=True)),
                ("show_start_time", models.TimeField(blank=True, null=True)),
                (
                    "expected_audience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("technical_notes", models.TextField(blank=True)),
                ("foh_notes", models.TextField(blank=True)),
                ("cast_notes", models.TextField(blank=True)),
                ("production_manager_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("distributed", "Distributed"),
                            ("confirmed", "Confirmed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("distributed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="show_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operating_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="show_calls",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="show_calls",
                        to="programming.performance",
                    ),
                ),
            ],
            options={
                "ordering": ["-show_date", "-call_time"],
            },
        ),
    ]
