# Generated by Django 5.2.14 on 2026-05-19 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_show_call_post_show_report"),
        ("organisations", "0002_organisation_popia_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("stage_manager", "Stage Manager"),
                            ("deputy_sm", "Deputy Stage Manager"),
                            ("lighting_op", "Lighting Operator"),
                            ("sound_op", "Sound Operator"),
                            ("follow_spot", "Follow Spot Operator"),
                            ("fly_op", "Fly Operator"),
                            ("head_of_wardrobe", "Head of Wardrobe"),
                            ("wardrobe_assistant", "Wardrobe Assistant"),
                            ("head_usher", "Head Usher"),
                            ("usher", "Usher"),
                            ("box_office", "Box Office"),
                            ("security", "Security"),
                            ("foh_manager", "Front of House Manager"),
                            ("production_manager", "Production Manager"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("call_time", models.TimeField()),
                ("finish_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "show_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_calls",
                        to="operations.showcall",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["call_time", "role"],
                "unique_together": {("show_call", "staff_member", "role")},
            },
        ),
    ]
