# Generated by Django 5.2.14 on 2026-05-21 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("operations", "0003_staff_call"),
        ("organisations", "0003_entity_config"),
        ("structure", "0004_venue_rental"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquorLicence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("licence_number", models.CharField(blank=True, max_length=100)),
                ("licence_holder", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not Applicable"),
                            ("required", "Required — Not Applied"),
                            ("applied", "Application Submitted"),
                            ("approved", "Approved"),
                            ("active", "Active / Paid"),
                            ("renewal_due", "Renewal Due"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="required",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "annual_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("last_paid_date", models.DateField(blank=True, null=True)),
                ("issuing_authority", models.CharField(blank=True, max_length=255)),
                ("conditions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquor_licences",
                        to="structure.venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyComplianceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "compliance_type",
                    models.CharField(
                        choices=[
                            ("fire_certificate", "Fire Safety Certificate (CoC)"),
                            ("evacuation_plan", "Evacuation Plan"),
                            ("crowd_management", "Crowd Management Plan"),
                            ("first_aid", "First Aid Compliance"),
                            ("ohs_inspection", "OHS Inspection"),
                            ("public_liability", "Public Liability Insurance"),
                            ("structural_cert", "Structural Certificate"),
                        ],
                        max_length=25,
                    ),
                ),
                ("is_compliant", models.BooleanField(default=False)),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("issuing_body", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operating_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_records",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="safety_records",
                        to="structure.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["compliance_type", "expiry_date"],
            },
        ),
    ]
