# Generated by Django 5.2.14 on 2026-05-22 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_liquor_safety"),
        ("organisations", "0003_entity_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnionAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "union",
                    models.CharField(
                        choices=[
                            ("saga", "SAGA (S.A. Guild of Actors)"),
                            ("musa", "MUSA (Musicians Union of SA)"),
                            ("equity", "Equity"),
                            ("saew", "SAEW (S.A. Entertainment Workers)"),
                            ("satawu", "SATAWU (Transport & Allied Workers)"),
                            ("other", "Other Union"),
                        ],
                        max_length=20,
                    ),
                ),
                ("agreement_name", models.CharField(max_length=255)),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "minimum_call_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=4,
                        help_text="Minimum call length in hours",
                        max_digits=4,
                    ),
                ),
                (
                    "overtime_threshold_hours",
                    models.DecimalField(decimal_places=1, default=8, max_digits=4),
                ),
                (
                    "overtime_multiplier",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
                ),
                (
                    "meal_break_provision_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=5,
                        help_text="Meal break required after X hours",
                        max_digits=4,
                    ),
                ),
                (
                    "turnaround_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=10,
                        help_text="Minimum rest between calls",
                        max_digits=4,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnionCallRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_category",
                    models.CharField(
                        help_text="e.g. Principal Actor, Swing, Ensemble, Stage Manager",
                        max_length=100,
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Rate"),
                            ("weekly", "Weekly Rate"),
                            ("per_performance", "Per Performance"),
                            ("rehearsal", "Rehearsal Rate"),
                            ("recording", "Recording Rate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("minimum_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="ZAR", max_length=3)),
                ("effective_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="operations.unionagreement",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["role_category", "rate_type"],
            },
        ),
        migrations.CreateModel(
            name="CrewCallUnionCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheduled_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("minimum_call_met", models.BooleanField(default=True)),
                ("turnaround_met", models.BooleanField(default=True)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("compliance_notes", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "staff_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="union_checks",
                        to="operations.staffcall",
                    ),
                ),
                (
                    "union_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.unionagreement",
                    ),
                ),
                (
                    "applicable_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.unioncallrate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
