# Generated by Django 5.2.14 on 2026-05-22 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("operations", "0005_union_agreements"),
        ("organisations", "0003_entity_config"),
        ("structure", "0005_rental_booking_invoice_resident"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("performance_date", models.DateField(blank=True, null=True)),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("wheelchair", "Wheelchair Access"),
                            ("hearing_loop", "Hearing Loop"),
                            ("audio_description", "Audio Description"),
                            ("sign_language", "Sign Language Interpretation"),
                            ("large_print", "Large Print Programme"),
                            ("braille", "Braille Programme"),
                            ("relaxed", "Relaxed Performance"),
                            ("carer", "Carer Admission"),
                            ("parking", "Accessible Parking"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("patron_name", models.CharField(blank=True, max_length=255)),
                ("patron_contact", models.CharField(blank=True, max_length=255)),
                ("details", models.TextField(blank=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accessibility_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operating_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_requirements",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AudienceComplaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("complaint_date", models.DateField()),
                ("complainant_name", models.CharField(blank=True, max_length=255)),
                ("complainant_email", models.EmailField(blank=True, max_length=254)),
                ("complainant_phone", models.CharField(blank=True, max_length=30)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("service", "Customer Service"),
                            ("facility", "Facility / Venue"),
                            ("technical", "Technical / Show Quality"),
                            ("safety", "Safety Concern"),
                            ("accessibility", "Accessibility"),
                            ("staff", "Staff Conduct"),
                            ("ticketing", "Ticketing / Pricing"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("acknowledged", "Acknowledged"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("requires_follow_up", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaint_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operating_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audience_complaints",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InspectionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("fire_safety", "Fire Safety"),
                            ("electrical_coc", "Electrical CoC"),
                            ("structural", "Structural"),
                            ("ohs", "OHS"),
                            ("lift", "Lift / Elevator"),
                            ("pressure_vessel", "Pressure Vessel"),
                            ("general", "General"),
                        ],
                        max_length=50,
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("inspector_name", models.CharField(max_length=255)),
                ("inspector_company", models.CharField(blank=True, max_length=255)),
                ("passed", models.BooleanField(default=True)),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("findings", models.TextField(blank=True)),
                ("corrective_actions_required", models.TextField(blank=True)),
                ("next_inspection_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_records",
                        to="structure.venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LateSeatingPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cutoff_minutes",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="Minutes after start time when late seating is no longer permitted",
                    ),
                ),
                ("holding_area", models.CharField(blank=True, max_length=255)),
                ("policy_description", models.TextField()),
                ("exceptions_allowed", models.BooleanField(default=True)),
                (
                    "exception_approval_role",
                    models.CharField(
                        blank=True,
                        help_text="Role that can approve exceptions e.g. House Manager",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operating_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_seating_policies",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electrical", "Electrical"),
                            ("plumbing", "Plumbing"),
                            ("structural", "Structural"),
                            ("hvac", "HVAC / Air Conditioning"),
                            ("stage_equipment", "Stage Equipment"),
                            ("lighting_infra", "Lighting Infrastructure"),
                            ("sound_infra", "Sound Infrastructure"),
                            ("it_systems", "IT / AV Systems"),
                            ("safety", "Safety / Fire"),
                            ("grounds", "Grounds / Exterior"),
                            ("cleaning", "Cleaning / Hygiene"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("biannual", "Bi-Annual"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_completed_date", models.DateField(blank=True, null=True)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_schedules",
                        to="structure.venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticket_number", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electrical", "Electrical"),
                            ("plumbing", "Plumbing"),
                            ("structural", "Structural"),
                            ("hvac", "HVAC / Air Conditioning"),
                            ("stage_equipment", "Stage Equipment"),
                            ("lighting_infra", "Lighting Infrastructure"),
                            ("sound_infra", "Sound Infrastructure"),
                            ("it_systems", "IT / AV Systems"),
                            ("safety", "Safety / Fire"),
                            ("grounds", "Grounds / Exterior"),
                            ("cleaning", "Cleaning / Hygiene"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical — Production Impacting"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("logged", "Logged"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("awaiting_parts", "Awaiting Parts / Contractor"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("escalated", "Escalated to Management"),
                        ],
                        default="logged",
                        max_length=20,
                    ),
                ),
                (
                    "location_detail",
                    models.CharField(
                        blank=True,
                        help_text="Specific location e.g. Stage Left, Dressing Room 2",
                        max_length=255,
                    ),
                ),
                ("is_production_impacting", models.BooleanField(default=False)),
                ("target_resolution_date", models.DateField(blank=True, null=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "cost_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("contractor_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_production",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_tickets",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_tickets",
                        to="structure.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueDowntime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("production_impact", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downtime_records",
                        to="operations.maintenanceticket",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downtime_records",
                        to="structure.venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
