# Generated by Django 5.2.14 on 2026-05-19 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contexts", "0001_initial"),
        ("organisations", "0002_organisation_popia_fields"),
        ("programming", "0005_season_show_performance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patron",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("general", "General Audience"),
                            ("subscriber", "Subscriber"),
                            ("vip", "VIP"),
                            ("youth", "Youth"),
                            ("educator", "Educator"),
                            ("corporate", "Corporate"),
                            ("media", "Media"),
                            ("donor", "Donor / Sponsor"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk-In"),
                            ("online", "Online Booking"),
                            ("phone", "Phone Booking"),
                            ("mailing_list", "Mailing List Sign-Up"),
                            ("schools", "Schools Programme"),
                            ("corporate", "Corporate Partnership"),
                            ("referral", "Referral"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=50)),
                ("marketing_opt_in", models.BooleanField(default=False)),
                ("popia_consent_given", models.BooleanField(default=False)),
                ("popia_consent_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_bookings", models.PositiveIntegerField(default=0)),
                (
                    "total_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("first_visit_date", models.DateField(blank=True, null=True)),
                ("last_visit_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="PatronAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("tickets_count", models.PositiveIntegerField(default=1)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("channel", models.CharField(blank=True, max_length=20)),
                ("is_comp", models.BooleanField(default=False)),
                (
                    "feedback_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("feedback_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operating_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patron_attendances",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="patrons.patron",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patron_attendances",
                        to="programming.performance",
                    ),
                ),
            ],
            options={
                "ordering": ["-attendance_date"],
            },
        ),
        migrations.CreateModel(
            name="PatronCommunication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("channel", models.CharField(default="email", max_length=20)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operating_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patron_communications",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="patrons.patron",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patron_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
