# Generated by Django 5.2.14 on 2026-05-21 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("organisations", "0003_entity_config"),
        ("patrons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Donor"),
                            ("corporate", "Corporate Sponsor"),
                            ("foundation", "Foundation / Trust"),
                            ("government", "Government Grant"),
                            ("arts_council", "Arts Council"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                (
                    "tax_exempt_number",
                    models.CharField(
                        blank=True, help_text="Section 18A PBO number", max_length=100
                    ),
                ),
                (
                    "is_section_18a",
                    models.BooleanField(
                        default=False,
                        help_text="Eligible for Section 18A tax deduction receipts",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("pledged", "Pledged"),
                            ("invoiced", "Invoiced"),
                            ("received", "Received"),
                            ("acknowledged", "Acknowledged / Receipted"),
                            ("lapsed", "Lapsed"),
                        ],
                        default="pledged",
                        max_length=20,
                    ),
                ),
                (
                    "amount_pledged",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("pledge_date", models.DateField()),
                ("received_date", models.DateField(blank=True, null=True)),
                ("section_18a_issued", models.BooleanField(default=False)),
                ("section_18a_date", models.DateField(blank=True, null=True)),
                ("purpose", models.CharField(blank=True, max_length=255)),
                ("conditions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operating_context",
                    models.ForeignKey(
                        blank=True,
                        help_text="Production or project this donation supports",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="patrons.donor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
