# Generated by Django 5.2.14 on 2026-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_executiveaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
