# Generated by Django 5.2.14 on 2026-05-19 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("documents", "0004_alter_document_file_size"),
        ("governance", "0003_correctiveaction_updated_at_risk_updated_at"),
        ("organisations", "0002_organisation_popia_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMeeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("ordinary", "Ordinary Board Meeting"),
                            ("special", "Special Board Meeting"),
                            ("committee", "Committee Meeting"),
                            ("agm", "Annual General Meeting"),
                            ("audit_committee", "Audit Committee"),
                            ("risk_committee", "Risk & Governance Committee"),
                        ],
                        default="ordinary",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("meeting_date", models.DateField()),
                ("venue", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("concluded", "Concluded"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("quorum_required", models.PositiveIntegerField(default=0)),
                ("quorum_achieved", models.BooleanField(default=False)),
                ("members_present", models.PositiveIntegerField(default=0)),
                ("apologies", models.TextField(blank=True)),
                ("chaired_by", models.CharField(blank=True, max_length=255)),
                ("minuted_by", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agenda_meetings",
                        to="documents.document",
                    ),
                ),
                (
                    "minutes_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minutes_meetings",
                        to="documents.document",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-meeting_date"],
            },
        ),
        migrations.CreateModel(
            name="BoardResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resolution_number", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("rejected", "Rejected"),
                            ("deferred", "Deferred"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="passed",
                        max_length=20,
                    ),
                ),
                ("proposed_by", models.CharField(blank=True, max_length=255)),
                ("seconded_by", models.CharField(blank=True, max_length=255)),
                ("votes_for", models.PositiveIntegerField(default=0)),
                ("votes_against", models.PositiveIntegerField(default=0)),
                ("votes_abstained", models.PositiveIntegerField(default=0)),
                ("action_required", models.TextField(blank=True)),
                ("action_due_date", models.DateField(blank=True, null=True)),
                ("action_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="governance.boardmeeting",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["resolution_number", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("financial_year", models.CharField(blank=True, max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for Approval"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("revised", "Revised"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_expenditure",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operating_context",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governance_budget",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("personnel", "Personnel"),
                            ("production", "Production"),
                            ("marketing", "Marketing"),
                            ("technical", "Technical"),
                            ("venue", "Venue & Facilities"),
                            ("travel", "Travel & Accommodation"),
                            ("admin", "Administration"),
                            ("contingency", "Contingency"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "actual_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="governance.budget",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "sort_order", "description"],
            },
        ),
    ]
