# Generated by Django 5.2.14 on 2026-05-20 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0004_budget_board_meeting"),
        ("organisations", "0003_entity_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DelegationMatrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                ("effective_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_delegation_matrices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DelegationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("procurement", "Procurement"),
                            ("contracts", "Contracts"),
                            ("human_resources", "Human Resources"),
                            ("finance", "Finance"),
                            ("operations", "Operations"),
                            ("legal", "Legal"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_description", models.CharField(max_length=255)),
                (
                    "delegated_to",
                    models.CharField(
                        choices=[
                            ("board", "Board"),
                            ("ceo", "CEO / Executive Director"),
                            ("cfo", "CFO"),
                            ("gm", "General Manager"),
                            ("department_manager", "Department Manager"),
                            ("staff", "Staff Member"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "threshold_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ZAR threshold — null means no financial limit",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("requires_countersign", models.BooleanField(default=False)),
                (
                    "countersign_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("board", "Board"),
                            ("ceo", "CEO / Executive Director"),
                            ("cfo", "CFO"),
                            ("gm", "General Manager"),
                            ("department_manager", "Department Manager"),
                            ("staff", "Staff Member"),
                        ],
                        max_length=30,
                    ),
                ),
                ("requires_board_approval", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="governance.delegationmatrix",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "threshold_amount"],
            },
        ),
        migrations.CreateModel(
            name="IUFWIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                (
                    "iufw_type",
                    models.CharField(
                        choices=[
                            ("irregular", "Irregular Expenditure"),
                            ("unauthorised", "Unauthorised Expenditure"),
                            ("fruitless", "Fruitless & Wasteful Expenditure"),
                            ("wasteful", "Wasteful Expenditure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("under_investigation", "Under Investigation"),
                            ("referred_discipline", "Referred for Disciplinary Action"),
                            ("referred_criminal", "Referred to Law Enforcement"),
                            ("condoned", "Condoned by Authority"),
                            ("recovered", "Recovered"),
                            ("written_off", "Written Off (Board Approved)"),
                            ("closed", "Closed"),
                        ],
                        default="identified",
                        max_length=25,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("discovered_date", models.DateField()),
                (
                    "responsible_description",
                    models.CharField(blank=True, max_length=255),
                ),
                ("root_cause", models.TextField(blank=True)),
                ("reported_to_board", models.BooleanField(default=False)),
                ("reported_to_ag", models.BooleanField(default=False)),
                ("agsa_reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="iufw_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IUFWInvestigation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "investigator_description",
                    models.CharField(blank=True, max_length=255),
                ),
                ("commenced_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("findings", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("disciplinary_recommended", models.BooleanField(default=False)),
                ("criminal_referral_recommended", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigation",
                        to="governance.iufwincident",
                    ),
                ),
                (
                    "investigator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="iufw_investigations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IUFWRecovery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_recovered",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("recovery_date", models.DateField()),
                ("recovery_method", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recoveries",
                        to="governance.iufwincident",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShareholderCompact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(help_text="e.g. 2025/2026", max_length=9),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to Shareholder"),
                            ("agreed", "Agreed & Signed"),
                            ("in_progress", "In Progress"),
                            ("under_review", "Under Review"),
                            ("closed", "Closed / Evaluated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("executive_authority", models.CharField(blank=True, max_length=255)),
                ("signed_date", models.DateField(blank=True, null=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "total_grant_allocation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "unique_together": {("organisation", "financial_year")},
            },
        ),
        migrations.CreateModel(
            name="FundingTranche",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tranche_number", models.PositiveSmallIntegerField()),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("due_date", models.DateField()),
                ("received_date", models.DateField(blank=True, null=True)),
                ("is_received", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "compact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tranches",
                        to="governance.shareholdercompact",
                    ),
                ),
            ],
            options={
                "ordering": ["tranche_number"],
            },
        ),
        migrations.CreateModel(
            name="CompactTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("financial", "Financial Performance"),
                            ("artistic", "Artistic Mandate"),
                            ("governance", "Governance & Compliance"),
                            ("social", "Social Impact"),
                            ("operational", "Operational Efficiency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("indicator_name", models.CharField(max_length=255)),
                ("baseline_value", models.CharField(blank=True, max_length=100)),
                ("target_value", models.CharField(max_length=100)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "weight_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("q1_target", models.CharField(blank=True, max_length=100)),
                ("q2_target", models.CharField(blank=True, max_length=100)),
                ("q3_target", models.CharField(blank=True, max_length=100)),
                ("q4_target", models.CharField(blank=True, max_length=100)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "compact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="governance.shareholdercompact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompactActual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Q1"), (2, "Q2"), (3, "Q3"), (4, "Q4")]
                    ),
                ),
                ("actual_value", models.CharField(max_length=100)),
                ("variance_notes", models.TextField(blank=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("evidence_reference", models.CharField(blank=True, max_length=255)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compact_actuals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actuals",
                        to="governance.compacttarget",
                    ),
                ),
            ],
            options={
                "unique_together": {("organisation", "target", "quarter")},
            },
        ),
    ]
