# Generated by Django 5.2.14 on 2026-05-20 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0005_sa_compliance"),
        ("organisations", "0003_entity_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AGAuditRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Financial Audit"),
                            ("performance", "Performance Audit"),
                            ("compliance", "Compliance Audit"),
                            ("interim", "Interim Audit"),
                        ],
                        default="annual",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("notice_received", "Audit Notice Received"),
                            ("preparation", "Preparation in Progress"),
                            ("fieldwork", "Fieldwork in Progress"),
                            ("management_comments", "Management Comments Stage"),
                            ("draft_report", "Draft Report Received"),
                            ("final_report", "Final Report Received"),
                            ("closed", "Closed"),
                        ],
                        default="notice_received",
                        max_length=25,
                    ),
                ),
                ("notice_date", models.DateField(blank=True, null=True)),
                ("fieldwork_start", models.DateField(blank=True, null=True)),
                ("fieldwork_end", models.DateField(blank=True, null=True)),
                ("draft_report_date", models.DateField(blank=True, null=True)),
                ("final_report_date", models.DateField(blank=True, null=True)),
                (
                    "audit_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clean", "Clean Audit"),
                            (
                                "unqualified_emphasis",
                                "Unqualified with Emphasis of Matter",
                            ),
                            ("qualified", "Qualified Opinion"),
                            ("adverse", "Adverse Opinion"),
                            ("disclaimer", "Disclaimer of Opinion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("management_response", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audit_coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinated_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AGAuditEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("financial_statements", "Financial Statements"),
                            ("governance", "Governance Documents"),
                            ("procurement", "Procurement Records"),
                            ("contracts", "Contracts"),
                            ("iufw", "IUFW Evidence"),
                            ("performance", "Performance Evidence"),
                            ("compliance", "Compliance Documents"),
                            ("hr", "Human Resources"),
                            ("other", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("document_reference", models.CharField(blank=True, max_length=100)),
                ("provided_date", models.DateField(blank=True, null=True)),
                ("is_provided", models.BooleanField(default=False)),
                (
                    "ag_query_ref",
                    models.CharField(
                        blank=True,
                        help_text="AG query/finding reference number",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "provided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ag_evidence_provided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="governance.agauditrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
