# Generated by Django 5.2.14 on 2026-05-21 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0006_ag_audit"),
        ("organisations", "0003_entity_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictOfInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("declaration_date", models.DateField()),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("declared_none", "Declared — No Conflict"),
                            ("declared_conflict", "Declared — Conflict Exists"),
                            ("recused", "Recused from Matter"),
                            ("pending", "Declaration Pending"),
                            ("overdue", "Declaration Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("financial", "Financial Interest"),
                            ("family", "Family / Personal Relationship"),
                            ("directorship", "Directorship / Trusteeship"),
                            ("employment", "Outside Employment"),
                            ("gift", "Gift / Benefit Received"),
                            ("tender", "Tender / Procurement Related"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Nature of the conflict or interest"
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of entity/person involved",
                        max_length=255,
                    ),
                ),
                (
                    "matter_reference",
                    models.CharField(
                        blank=True,
                        help_text="Specific matter, contract, or tender reference",
                        max_length=255,
                    ),
                ),
                ("recusal_details", models.TextField(blank=True)),
                ("is_annual_declaration", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "declarant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "witnessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="witnessed_declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-declaration_date"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "financial_year"],
                        name="governance__organis_89fd5f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Q1"), (2, "Q2"), (3, "Q3"), (4, "Q4")]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for Review"),
                            ("reviewed", "Reviewed by Executive"),
                            ("approved", "Approved by Board"),
                            ("published", "Published / Shared with Shareholder"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("reporting_period_start", models.DateField()),
                ("reporting_period_end", models.DateField()),
                ("executive_summary", models.TextField(blank=True)),
                ("key_achievements", models.TextField(blank=True)),
                ("challenges", models.TextField(blank=True)),
                ("corrective_actions", models.TextField(blank=True)),
                ("financial_narrative", models.TextField(blank=True)),
                ("submitted_date", models.DateField(blank=True, null=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_performance_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reports",
                        to="governance.shareholdercompact",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_performance_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["compact__financial_year", "quarter"],
                "unique_together": {("organisation", "compact", "quarter")},
            },
        ),
    ]
