# Generated by Django 5.2.14 on 2026-05-21 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0007_conflict_interest_performance_reports"),
        ("organisations", "0003_entity_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMemberProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "role_title",
                    models.CharField(
                        help_text="e.g. Chairperson, Non-Executive Director",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resigned", "Resigned"),
                            ("term_expired", "Term Expired"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("term_end_date", models.DateField(blank=True, null=True)),
                ("term_number", models.PositiveSmallIntegerField(default=1)),
                ("appointing_authority", models.CharField(blank=True, max_length=255)),
                ("qualifications", models.TextField(blank=True)),
                ("expertise_areas", models.CharField(blank=True, max_length=255)),
                ("committee_memberships", models.CharField(blank=True, max_length=255)),
                ("is_independent", models.BooleanField(default=True)),
                ("annual_declaration_submitted", models.BooleanField(default=False)),
                ("annual_declaration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="board_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "appointment_date"],
            },
        ),
    ]
