# Generated by Django 5.2.14 on 2026-05-22 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0008_board_member_profiles"),
        ("organisations", "0003_entity_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("drafting", "Sections Being Drafted"),
                            ("review", "Under Internal Review"),
                            ("board_approval", "Awaiting Board Approval"),
                            ("approved", "Board Approved"),
                            ("submitted", "Submitted to Executive Authority"),
                            ("published", "Published / Tabled in Parliament"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("theme", models.CharField(blank=True, max_length=255)),
                ("ceo_message", models.TextField(blank=True)),
                ("chairperson_message", models.TextField(blank=True)),
                ("tabling_date", models.DateField(blank=True, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("approved_by_board_date", models.DateField(blank=True, null=True)),
                (
                    "overall_audit_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clean", "Clean Audit"),
                            (
                                "unqualified_emphasis",
                                "Unqualified with Emphasis of Matter",
                            ),
                            ("qualified", "Qualified Opinion"),
                            ("adverse", "Adverse Opinion"),
                            ("disclaimer", "Disclaimer of Opinion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "unique_together": {("organisation", "financial_year")},
            },
        ),
        migrations.CreateModel(
            name="AnnualReportSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("part_a", "Part A — General Information"),
                            ("part_b", "Part B — Performance Information"),
                            ("part_c", "Part C — Governance"),
                            ("part_d", "Part D — Human Resources"),
                            ("part_e", "Part E — Financial Statements"),
                            ("supplementary", "Supplementary Information"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("draft_complete", "Draft Complete"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annual_report_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="governance.annualreport",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "section_type"],
            },
        ),
        migrations.CreateModel(
            name="IUFWCondonement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("condoned_by_board", models.BooleanField(default=False)),
                (
                    "board_resolution_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("condonement_date", models.DateField(blank=True, null=True)),
                ("motivation", models.TextField(blank=True)),
                ("treasury_notification_required", models.BooleanField(default=True)),
                ("treasury_notified_date", models.DateField(blank=True, null=True)),
                ("ag_disclosure_required", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condonement",
                        to="governance.iufwincident",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IUFWDisciplinaryReferral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("referral_date", models.DateField()),
                ("employee_name", models.CharField(max_length=255)),
                ("charge_description", models.TextField()),
                ("hearing_date", models.DateField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Hearing Pending"),
                            ("guilty_dismissal", "Guilty — Dismissed"),
                            ("guilty_final_warning", "Guilty — Final Written Warning"),
                            ("guilty_other", "Guilty — Other Sanction"),
                            ("not_guilty", "Not Guilty"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sanction_details", models.TextField(blank=True)),
                ("appeal_lodged", models.BooleanField(default=False)),
                ("appeal_outcome", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_referrals",
                        to="governance.iufwincident",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="iufw_disciplinary_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Section32Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Month 1"),
                            (2, "Month 2"),
                            (3, "Month 3"),
                            (4, "Month 4"),
                            (5, "Month 5"),
                            (6, "Month 6"),
                            (7, "Month 7"),
                            (8, "Month 8"),
                            (9, "Month 9"),
                            (10, "Month 10"),
                            (11, "Month 11"),
                            (12, "Month 12"),
                        ]
                    ),
                ),
                ("reporting_period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("submitted", "Submitted to Treasury"),
                            ("acknowledged", "Acknowledged by Treasury"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_revenue_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_revenue_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_expenditure_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_expenditure_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "grant_receipts_ytd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "fruitless_wasteful_ytd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "irregular_ytd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("submitted_date", models.DateField(blank=True, null=True)),
                ("treasury_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="section32_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["financial_year", "month"],
                "unique_together": {("organisation", "financial_year", "month")},
            },
        ),
        migrations.CreateModel(
            name="Section32ProgrammeLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("programme_name", models.CharField(max_length=255)),
                (
                    "budget_allocation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "expenditure_ytd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "expenditure_this_month",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("variance_explanation", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programme_lines",
                        to="governance.section32report",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
