# Generated by Django 5.2.14 on 2026-05-22 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0009_section32_annual_report_iufw_extensions"),
        ("organisations", "0003_entity_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiryAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("csd_verification", "CSD Verification Expiry"),
                            ("tax_clearance", "Tax Clearance Expiry"),
                            ("bee_certificate", "B-BBEE Certificate Expiry"),
                            ("liquor_licence", "Liquor Licence Expiry"),
                            ("safety_cert", "Safety Certificate Expiry"),
                            ("inspection", "Venue Inspection Due"),
                            ("insurance", "Insurance Policy Expiry"),
                            ("contract", "Contract Expiry"),
                            ("board_term", "Board Member Term Expiry"),
                            ("delegation", "Delegation Matrix Review Due"),
                        ],
                        max_length=25,
                    ),
                ),
                ("reference_description", models.CharField(max_length=255)),
                ("expiry_date", models.DateField()),
                (
                    "days_warning",
                    models.PositiveSmallIntegerField(
                        default=30, help_text="Alert X days before expiry"
                    ),
                ),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("auto_created", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_expiry_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
            },
        ),
    ]
