# Generated by Django 5.2.14 on 2026-05-07 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contexts", "0001_initial"),
        ("documents", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("artist_performance", "Artist Performance"),
                            ("co_production", "Co-Production"),
                            ("venue_hire", "Venue Hire"),
                            ("supplier_service", "Supplier Service"),
                            ("sponsorship", "Sponsorship"),
                            ("facilitator", "Facilitator"),
                            ("partnership", "Partnership"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                ("template_fields", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContractRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("artist_performance", "Artist Performance"),
                            ("co_production", "Co-Production"),
                            ("venue_hire", "Venue Hire"),
                            ("supplier_service", "Supplier Service"),
                            ("sponsorship", "Sponsorship"),
                            ("facilitator", "Facilitator"),
                            ("partnership", "Partnership"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("counterparty_name", models.CharField(max_length=255)),
                (
                    "counterparty_type",
                    models.CharField(
                        choices=[
                            ("artist", "Artist"),
                            ("supplier", "Supplier"),
                            ("partner", "Partner"),
                            ("client", "Client"),
                            ("government", "Government"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="ZAR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("legal_review", "Legal Review"),
                            ("finance_review", "Finance Review"),
                            ("scm_review", "SCM Review"),
                            ("issued", "Issued"),
                            ("counter_signed", "Counter Signed"),
                            ("signed", "Signed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("signatures_required", models.IntegerField(default=2)),
                ("signatures_received", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operating_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "signed_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_contracts",
                        to="documents.document",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="contracts.contracttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignatureRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signatory_name", models.CharField(max_length=255)),
                ("signatory_role", models.CharField(max_length=255)),
                (
                    "signature_type",
                    models.CharField(
                        choices=[
                            ("wet", "Wet"),
                            ("electronic", "Electronic"),
                            ("digital", "Digital"),
                        ],
                        max_length=20,
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("is_signed", models.BooleanField(default=False)),
                ("signature_order", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="contracts.contractrecord",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["signature_order", "created_at"],
            },
        ),
    ]
