# Generated by Django 5.2.14 on 2026-05-07 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contexts", "0001_initial"),
        ("documents", "0001_initial"),
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketingSetup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("webtickets", "Webtickets"),
                            ("computicket", "Computicket"),
                            ("ticketpro", "Ticketpro"),
                            ("internal_rsvp", "Internal RSVP"),
                            ("not_ticketed", "Not Ticketed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("booking_link", models.URLField(blank=True)),
                ("pricing_description", models.TextField(blank=True)),
                ("comps_allocated", models.IntegerField(default=0)),
                ("comps_used", models.IntegerField(default=0)),
                (
                    "setup_status",
                    models.CharField(
                        choices=[
                            ("awaiting_setup", "Awaiting Setup"),
                            ("in_progress", "In Progress"),
                            ("live", "Live"),
                            ("closed", "Closed"),
                        ],
                        default="awaiting_setup",
                        max_length=20,
                    ),
                ),
                ("sales_imported", models.BooleanField(default=False)),
                ("tickets_sold", models.IntegerField(default=0)),
                ("tickets_available", models.IntegerField(default=0)),
                (
                    "settlement_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("settled", "Settled"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "settlement_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operating_context",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticketing_setup",
                        to="contexts.operatingcontext",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("import_date", models.DateField(auto_now_add=True)),
                ("tickets_sold", models.IntegerField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_imports",
                        to="documents.document",
                    ),
                ),
                (
                    "ticketing_setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_imports",
                        to="ticketing.ticketingsetup",
                    ),
                ),
            ],
            options={
                "ordering": ["-import_date"],
            },
        ),
    ]
